/* Exception observers for outcome type
(C) 2017-2020 Niall Douglas <http://www.nedproductions.biz/> (3 commits)
File Created: Oct 2017


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_OUTCOME_BASIC_OUTCOME_EXCEPTION_OBSERVERS_HPP
#define BOOST_OUTCOME_BASIC_OUTCOME_EXCEPTION_OBSERVERS_HPP

#include "basic_result_storage.hpp"

BOOST_OUTCOME_V2_NAMESPACE_EXPORT_BEGIN

namespace detail
{
  template <class Base, class R, class S, class P, class NoValuePolicy> class basic_outcome_exception_observers : public Base
  {
  public:
    using exception_type = P;
    using Base::Base;

    constexpr inline exception_type &assume_exception() & noexcept;
    constexpr inline const exception_type &assume_exception() const &noexcept;
    constexpr inline exception_type &&assume_exception() && noexcept;
    constexpr inline const exception_type &&assume_exception() const &&noexcept;

    constexpr inline exception_type &exception() &;
    constexpr inline const exception_type &exception() const &;
    constexpr inline exception_type &&exception() &&;
    constexpr inline const exception_type &&exception() const &&;
  };

  // Exception observers not present
  template <class Base, class R, class S, class NoValuePolicy> class basic_outcome_exception_observers<Base, R, S, void, NoValuePolicy> : public Base
  {
  public:
    using Base::Base;
    constexpr void assume_exception() const noexcept { NoValuePolicy::narrow_exception_check(this); }
    constexpr void exception() const { NoValuePolicy::wide_exception_check(this); }
  };

}  // namespace detail

BOOST_OUTCOME_V2_NAMESPACE_END

#endif

/* basic_outcome_exception_observers.hpp
FjkvpN+lyL/3fUew3BfGPvWu54JWYqk4yDuDNmTV9MfWDzYf5KlzzPOFeeX4veg9bBy7y3guG2lNx7xunhHqOl4w38/Gsa6rfsmSJ9+Vx1wt8ph/D2IcW5mmVfW/6xiJ8oxhRY6FKpnLc3M8E2SqiymvKtPDeI+I+RhDfrO5VW3f1HN4VfeAxs7uWkXeuRy22rngUxio90iyOM/Tt7Qwnaff8+ea7p+Js0/lHWr5QbO7f19Yi3v/LrEsHlTDfSxJ3KF/hmOZn9HNebe5HPO5nOv+/KYt9eEXyD2Ba6WlzL/rMr8fyXXM+IUqr5vlBHPI+B7lptzb+RfeIm4TZNAshLFOTb3H73Idbq6/vN7y761D7n6Ta77OYl/nHMGHBD04a5XvVVrdtfzGsWboHSkJ9/g9wxqVZ5sWT/kZhLtlR7nuf8cgy36lGr6L3wB7quM89ZsjIx+1HKU1Ni9DV3mFx/SF1XQ9m0/KKFBpG8v57Z1pzee3+rFGOO160xrnNtTLamvOTZCeJUhzv/sgP1Lll3Htd+q2Vue2Re9jlHsQnX8fqzw1Xfc2ehDrVL++zONKktai0kp5rvsaPUz91Lm33MPcM4fjuDVyLbcdR1IezuNJO/0iCbm26tFJk32UDOtLzFHHKu1cx2VGeesYpn7L0JzyrJ6qvGi9rMLyrG2kPGNYDjHbyGOzqmFG1JN5POhV5zzm8q1fdb8Iv+rcfVqiyN2nnla389213m1V8ytVG8YckfNAmS9h97zn9C2VJ+hvLasNsqwCTctqm97vbywnvW1tYb7cXCvfJ3tV1Weor3Gv6Tr65xPOe03rmu81VcMKCHWNXWXzcM1To9zoV41zggA/Hy91T44qV6N/BGEsqyqyrIJlWBQx25TPVuR7YeO37hb5jbv5OVT+/2ab1aP139tmVTK/u8/N+mzeX5uHG9u2K6jZ2B7Rbvwta7Z57a7Zat6NxsvtGx+LWvoBzxD01PuPr1w7ZHuZRVtvTHpz1kezf+tPG7fp/fu8ua73N7c3d/tlwwvZvhurc3zxjK/ev+X1WjWjrk2ZuanLwLKXvOdMo9166/0POkrmDo6I2N/a86Fm4yt1Ks+5hqb3v9y+T4UJtebNfadsy3k+p2/9SJVUOcHvTpl7s2r02zNTu2+dsef1oxxjqfQ5n5Vo9oyt119dapR4+8MaZ95T70em/66P3/jsz/Jdnj7YNumjQxH757GvVfVMCZ59Nb3f0oHP1Bmwwj/C5xy/R/PT+9v2BsQMG1931dKN2wbcCj06nPW6sSr/2+OnBuwf+3TWsozs6GW/vM9zVlR91r+8puN0D9ut9sObbhj3bVPWkWaqnEtzQ16qe2DczfTfct7KyKm8mfdkqPEm5o2dcfVyzfeOP9+hQtjZyL1cK/HR+wc5Yrp91O/S2DrVl8yeMmnDVdqImv+Zr7706XeHw8PTDz+cGvfc2kscs6n6vP1U6oX186I7Vf1pQo/rc/uXpg3Y9f4VPxvuF/9kj+mnfGYkVqvdl4eK91T1fHP++IVhc3eNOFPmr01Xa1WJ4HkxKv2aJSP6b/f46eu3V9e4vXTRLLYpj6jlcjP/n/YXp6Zndfni2tC4x6uf5rkJqn/n3sODz0ZfCfNJrHB6WuMC6j9ftYdr13xfXFd/XmbL99OSgxp/yw7+UzX/Nz42OfqS17w1U9eVPH107YIDHDeo6bWujgutNvVas+CC4IDSO4d9yTVsNb3h4Wuivv/kz7L9Tz5dof+KCkf4TZaX3n9y4JJ//nN88CN5q0bvPF378Sasq6qcN9r0vHKzeZPjiy+cOTzcMvwY12XVdH3y9PH3bl+df2XSnMpl3pj7OGWUUvVsExJ77R8=
*/