/* UPDATED BY SCRIPT
(C) 2017-2020 Niall Douglas <http://www.nedproductions.biz/> (225 commits)


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

// Note the second line of this file must ALWAYS be the git SHA, third line ALWAYS the git SHA update time
#define BOOST_OUTCOME_PREVIOUS_COMMIT_REF f2fce2dc31cd1050c4693d1eea852a08c98fc164
#define BOOST_OUTCOME_PREVIOUS_COMMIT_DATE "2020-03-12 10:35:46 +00:00"
#define BOOST_OUTCOME_PREVIOUS_COMMIT_UNIQUE f2fce2dc

/* revision.hpp
+9V60LEEy0TKsk2553rgWq7nVP7HZL0wyrNaHNqHpncN8iz1B1gXRsi6EGxsez3oLtLegs3vppV2Yt42538s61CR4/CbAYXnQ95yPjSZNG2Pu9YhZwPSX5KQkHTHOhMq60xnlXYTZXpr0UQ8MZdY7f48k7LvbKMWUxsNleXRQ6VZq4WzJvQnRhAziOVu98muMt0u41Bp9w+rNK9o9fm3HxFLPEMsI+TZ0Sxfc5u57/6xu5tl5No/nlfdMl1FjiOHyMO6m8n5fGNjf3jCNc+T2W6Z3xloLE2350FtVL4a7uY1ZbqZL/p20LSNGqjS+Lp5hyzn7qZ0fVQ6P9c6GaO6PYuWrc6XjfcQGMcaFWRe2s3Xwx7gWKPAeC+Aqd5B5vcFmMZpPr86Ig8zeFxGMJCYSsNKu2Meu47UhyVMGKeWk+ynXW3SSGE+H8lWZTSkHkHu3xdeZJ5b3LyfLFOlGeC2LZO/yPvCVfXcbu8l7b891/kXe2ceWEVxBvDd93KRFyAJIYRwhfuU+5JDuUFBREFEREJIggQICTk4KmpQ6lE80CqithVrtVatogJaVERFRTyKiooWFa1WpdRSPEpba/vb7327b/KyLwlo2z9KdPi9OXfmm29mZ2dnZ9wzOERmPmXzH9dFnXmt+TDlPE0PqduKcXm+04Df8ORMYkXzVvA4m1dW7D4TStnSjTkmPzmShu/ZFz21HlqJfz/RwURMQ0wTTHNMG0xHTHcrvk7ZNLJSAGV00jPsU9TunBUzKvy7w6TJffpa6jYs4tbHPT9moOd2oth7e/bBYu/m2QeJvYNnHyj21p59gNizPHt/d54QRua6zLrgXip/aURIgKmwCrdDRl2ovpdXlpaWlFUwoowaB7lj0a8kTsju7tSA7fssRbq1P0tlwGFvOmGesDb5n29CGrGfpWQvUonfQMf+tqa3zboXt0f8nm81XicJl6nPUr5x5dz6GRR2UzO9r0817uttGqQkd9CzizVcSpaGq7rTCNiuQfQ4mOSsk+RaW9nLM1Hd3OtvJs2HvtPYeF49nsX2vOk/Zu7RXL9R0IRz9N4z5a2Ae5ZKPscKVZRV5svkp3OGj3uqUWlhfvT9R9rwNInbyk9HSLd+/VN032/q9d5s/lF9ToSN4SGEXOWX53nMz5fPR7H952wvkzhB+5/kzie/pFl93tA25g199JfwUXPmOn/o21drWPM8W7edPCB++6231F/nbT19/rH4f8WZ4/He2Paa1LApTT325/gtYtcymv09pqmWxdGne9/y5jHFPmdv9XndIVpXHVrq9fG0YYh/vkDw+/e6daU1lItuFZTPZ4rXd0zzsYRPsP3qiLQ8mQ+TeMvKK/zqJypsvOQwf655L7/+bce/hYx+3HHNRnELWq2RcwJhVhAwBUVviGmkprHbXo9iPOPOLw5z7JJnla1cz6K3ry7LPa3CiZVpf74Erkbevd9xZSnPt8XMDufRTOeWFKyoJstsleUACV9oN0cij/PrPN/+XNNVWbWTcQfV7ydXI2yy3sd5s+nNz8wSv+H2VfieYCf7nt98oYSZSx83Wd04ZVLcuiL59mYb8N4/5Yv/APtCYnS0Q179pKaHz6VLgJjwmVXH0Cbc+qHs2Cm71s8Fcl3W06vun/k7/3dLOTnhxD/S+vo9PNfJ+D7f+ppfmEeji+qnWmudxUuc9+w4ThwdQX1NwtyB0XM/Nc0Se6TVjjvKT816xC96/Fhc4dt/GWHNOsrWOhopfo3tdoyeNzDbdgipuPOSOeI30E6yhvIu8DHzfZX3vPCjd3VeQO8TT4i9c7W6ba06kyLpPWq/ybzrYDtgDaV+r7QzrEzjWSR/aYGOHyNzElMk3gdWE/I=
*/