/* Exception types throwable
(C) 2017-2020 Niall Douglas <http://www.nedproductions.biz/> (9 commits)
File Created: Oct 2017


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_OUTCOME_BAD_ACCESS_HPP
#define BOOST_OUTCOME_BAD_ACCESS_HPP

#include "config.hpp"

#include <stdexcept>

BOOST_OUTCOME_V2_NAMESPACE_EXPORT_BEGIN

/*! AWAITING HUGO JSON CONVERSION TOOL 
type definition  bad_result_access. Potential doc page: `bad_result_access`
*/
class BOOST_OUTCOME_SYMBOL_VISIBLE bad_result_access : public std::logic_error
{
public:
  explicit bad_result_access(const char *what)
      : std::logic_error(what)
  {
  }
};

/*! AWAITING HUGO JSON CONVERSION TOOL 
type definition template <class S> bad_result_access_with. Potential doc page: `bad_result_access_with<EC>`
*/
template <class S> class BOOST_OUTCOME_SYMBOL_VISIBLE bad_result_access_with : public bad_result_access
{
  S _error;

public:
  explicit bad_result_access_with(S v)
      : bad_result_access("no value")
      , _error(std::move(v))
  {
  }
  /*! AWAITING HUGO JSON CONVERSION TOOL 
SIGNATURE NOT RECOGNISED
*/
  const S &error() const & { return _error; }
  /*! AWAITING HUGO JSON CONVERSION TOOL 
SIGNATURE NOT RECOGNISED
*/
  S &error() & { return _error; }
  /*! AWAITING HUGO JSON CONVERSION TOOL 
SIGNATURE NOT RECOGNISED
*/
  const S &&error() const && { return _error; }
  /*! AWAITING HUGO JSON CONVERSION TOOL 
SIGNATURE NOT RECOGNISED
*/
  S &&error() && { return _error; }
};

/*! AWAITING HUGO JSON CONVERSION TOOL 
type definition  bad_outcome_access. Potential doc page: `bad_outcome_access`
*/
class BOOST_OUTCOME_SYMBOL_VISIBLE bad_outcome_access : public std::logic_error
{
public:
  explicit bad_outcome_access(const char *what)
      : std::logic_error(what)
  {
  }
};

BOOST_OUTCOME_V2_NAMESPACE_END

#endif

/* bad_access.hpp
wgHwTjgQZsNBcA68Hc4X/f1wMHxa9Pvhs6pc4BB4FA5V5QGHwVNwNDwNx6jygONhDpwAf4GZ8A84Cdp+y5oME+AUWBTeAYvBqbCU6FPhNNgAToedxLyP36RnAJwBh8KZMBPOhXPhAlW/cBl8HD6m8gPvhjvhPfA5uAjugw/Ak/BBlX74D/gWXKXqEa5W9QMfhj/BNfB30YeEmPSEwbUwBq6HJeAmWBluVvUm+hqibwy3qHqEW6FqY0/CvnAbHASfhiPgM3Aq3K7qT+JbLuZrRb8O7lD5hbvhdrgX7oD7VD7hfngYHlByDV9W9QQPwavwMIwO5XkOC8EjSv5EnwSPwRR4CpaDr6v8wdMqX/AdWAu+C+vBN1R7hH/SfluKuew/lm8oM7bw2H98k5w3KCnniErI+ZZkOUeTYpvnYjk5x1JezmdUgGmwrm2elxVhH93fm/eU1WU/ck04D6bCtaLfbJnzP1vF/5OWOTf0ouhfgqXgIdHLc0S++8s7fI/nyP1+8xx5ACYoN36Tnwf9Zlz8D78ZZz8EK+r1aDO+XA/TRT9c7NU44jE4GT4O74Wb4QN6fds8l5+Q+etT8h4Ymdfp3a7nq+hlfroTVoa7YFW4B9aEe/2m/98H68MDsC180W/60Zdgf9EPhofgSHgYToNH4Dx4FN4NN8L7RC/v++UbmYyNreD3/Tm2eY5csc049Tc5J/G77Du/Cm8WfQv4F2wj5xQ7KHmB3ZVWnr9+OFDMB8v5RH1fN5yhz+Ga9bjC8jwuAteLfhtMhNtVGuE+8a/ktQQ8ocKV53I4PCt6GZfJNxnpKz3GZXfI/GOWz8wD74KllD+fGf/N8Zn50FxYCy6S9YylsAu812fkfb7Kr+jTxH6I6J3zFtmSjts9zlvslnMH++T5/YKcu3hF9t3sl3MWB6CS6xdhVbFPtZAH2ES1Z9hR9D0t5EKe97jT9fAyHCh6eY9M5CZd5TzeI2fKuaCJci5okpw3mxo4p4Pafe33yH1x5+wTD4WDXOfQWoi/6h7z/73ib7+cQ3pJzp8elPOGL8PKKn+wiioXWE30TvjZEn6KR/hHJPxjlszTYJzoi6v5kJx3OmmZcj8By4jeKbftTvge5TZaym2MZdYTxor/cVbufpBz4v/toP0gUNL3qZxvOifp+Uzy/bll6v+8Zer5kmX61cuW6a9+gSP1HMDMB3+Fk+Uc2zQdv2l3OZYZ7/8bLpFznvfI+U8ls99aZv7xp2X2T/1lmf7Mss17NNs251xC4THot80+8xD4ljaX+nC+QwbbeNRHGWmH5WEIrADjYVUZ56f6TPlVhhXFvLWYy/q3fEOLPtlj/btkrKmP0jBFxSfrHCmwEywLuym5hWkqfjgAVow15VQJzlbxw2wVP5yvZDfW7PupATep9EA5DyffcSIMSY/7PNxQkY9hsIic942X88DJcg64gusccByO0yS8rvJ8K23K2dJyEivnF2GcqudY0z8XL2D652/Qd1T1CXuIvpeqZzgMfgfHwe/hVFVXcJGSC7hUyQW8H/4EV0o4G+FVWXf2FTD9sR++pvJawPTD4TJfiIDnYAz8CsbC71W+4CVYCEap+YGckykCK8AEWA0mwlYwSfVvts6XrH/J93X0t4OC179OSr2fhoXgmVjTHj+CxeAbMu9/E5YT8/KqTcbK+YtY067ehXr9AI4XdxPUfBxOgR/IuuqHppywd51z3y/nP4LWH3CvxuHKfUEjBx8XNOn5BNZU9VrQ1N852e/1GRyg2j8cr+obyrxfvvtCmB7z/tlyTnmhPL8XyXlk59zjEluea7YZ5yyzjTwst03+7pfx2gNwiZyfXKfGTbaR+1W2WSdYDfdJuPvhvfA=
*/