/* A less simple result type
(C) 2017-2020 Niall Douglas <http://www.nedproductions.biz/> (7 commits)
File Created: June 2017


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_OUTCOME_BOOST_OUTCOME_HPP
#define BOOST_OUTCOME_BOOST_OUTCOME_HPP

#include "std_outcome.hpp"

#include "boost_result.hpp"

#ifndef BOOST_SYSTEM_BASIC_OUTCOME_FAILURE_EXCEPTION_FROM_ERROR
#define BOOST_SYSTEM_BASIC_OUTCOME_FAILURE_EXCEPTION_FROM_ERROR
namespace boost
{
  namespace system
  {
    // Implement the .failure() observer.
    inline boost::exception_ptr basic_outcome_failure_exception_from_error(const boost::system::error_code &ec)
    {
      return boost::copy_exception(boost::system::system_error(ec));
    }
  }  // namespace system
}  // namespace boost
#endif

BOOST_OUTCOME_V2_NAMESPACE_EXPORT_BEGIN

/*! AWAITING HUGO JSON CONVERSION TOOL
SIGNATURE NOT RECOGNISED
*/
template <class R, class S = boost::system::error_code, class P = boost::exception_ptr, class NoValuePolicy = policy::default_policy<R, S, P>>  //
using boost_outcome = basic_outcome<R, S, P, NoValuePolicy>;

BOOST_OUTCOME_V2_NAMESPACE_END

#endif

/* boost_outcome.hpp
+pW4s/WOtKR7zK06Up3Xso6Y99EO1oQugwK8j7I6F4V1RURGTa4gk2sba+sbuTXMJneVA/UjcUfw/Exb3Wnabot630E0nrWUx2+4J4Xu9E5j/N8DZp43Su/Pt5d3tJZ3Q47/gAYiFYK14O/50eSXN6aIXjeYcIdLB7076FbhbWcrG+kk3UUlXanfBvWOR+GpdMudF/mumW3VT01HdOVJ6XPruPQpJuOvSPg4tyNfBm39pBm/WPqlGuYnjaEunjzLCy+x9plm3Ea/z6xxbP1lAu8bnkC1jQT33N8j4Re5k9w0zYveX2XMXx4TntFuX7dd0n3RXpJbJXy8e4KbmdR2gru3vy08vdxObpbvh+tp8RvoRvCP3dFYu4xnh3fB+nqs/v41Q2H7vlxkpHem4f6OpPc5ws8z767Vu57KF5RSrOWIKoifJ/F7hHd8PyXuE+kh0p1eUDAGfELv+Ml9x/eyhjoW3nOHzuCvOqN9P7LHT/QAP71jyfPT+o27j1XlFH+nqymjcZ06eOXRscZzf1XdBbjNe5MOaMGGqm4Pge6l0kpmJ7a5hdX+HYn2/naW8HeytTtNyz4eBHpWKTxdqNF0a5vTNKx998USNjBl3/0BCe/rHKOfPtvsp73yddHySV220G/ta69ncPsgdl6/K2Q+kSTD6qVUr7ZHQ4ZajtuEv6d97mYrv8r+dgnrnrL86yU8Kxy7Hprduj4+kAd5VXnE38s40/tfbSMz9Hzue5DdjqRye/nxO22z7GZf9DeJs4nWm24t/47UOhTeefeS8HzX6UGMBvt9l5qOfU6r8mSjuC8vS9+t8e1z3O7aJz4nPD912vH/EOgayNKXk1bb5r87Zrdt/rtjdtvmv8pv6FHjkjqPR/VzishlITOHTF9ncZ0lfpkyV9vfnhh5/lwtOk5ma9wvmxGJ5nFnbVamte2+Lc+cnJReKl1Ol/ABvtvgN+/TnsfzP9CK+19j+t1ye/93zt2DfqaoQM+YV128F+qG4jdfnNjeJH7c/Ki7trO3hHe9czr/X4iGVlvnSpqmfa5ka1fKb2+fwV2YfS7xeK5w8njm+9jdPQWytTEzLcY7TauirLHMvo60P9u7e9rajuC3zaGsbQhe+xwq6CsiUqbe4TqjWNyFss7oTpsogWl+53D9kts/Z4g0Bltb6CJxV6TU/a4Svsy65sh9h3MS1etkfTfvfzTkr3qt/IGc9f5Hc86i85AbvDyrvpu6PKCLn9kzIS/8DOgL3thxSYIusw6trVtljBsVDZQhlMlvhb/IpsOalmvMWRrqy53YvPRpCZ/ETa+uVac1fjgXfDyv9e+d/D6FvKpfVjCv0DyY67zD8Mp4qrbG56gsiudYZVG6sKZsESpolUlncLQXz76+I02LTDRuIXiihL/fKg+Ni5+pnxpfZTpYeMYm9fWezgyUsKkyVgwk0U2FOlbk0zLS0nIycwbkjOVnhIeZ8YO6HjtH25r2/SPEPZ689k1uM9o+xwvPydo+iaP5y8LPa0dtGyOOXZ+q28yBdC9e8C5P54NNyfXpDRhJcyJLvRE3Xhcvz2v9u6nE+dthOW+h7fcy2u/vTH3/pf0ex1T3U7b9PlT7vaep7xO134ea6j7R9+6e1MeHeP6vbd8RKevWdd3uXd+9/NffvO/W1Pd32u89bfv9pvb7YlPdS9r2+0ft97+mvlfVfn9q6vtW7fePprpnNPW9qn8K27Xf31S5/jxA7eL0G4P0u4QZdnG6/8rD34LdwGawJ3gY7OWlAZ4tbt3XGrxHBos0vQjYU9P7q6Z31Lw3S/lPV35zP95Plf9n4ATw56DmW9/VUSZLvl3XjxcBR4HdwNFgD3AM2BWEF7efXpar74s=
*/