/* Tries to convert an exception ptr into its equivalent error code
(C) 2017-2020 Niall Douglas <http://www.nedproductions.biz/> (11 commits)
File Created: July 2017


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_OUTCOME_UTILS_HPP
#define BOOST_OUTCOME_UTILS_HPP

#include "config.hpp"

#include <exception>
#include <string>
#include <system_error>

BOOST_OUTCOME_V2_NAMESPACE_BEGIN

#ifndef BOOST_NO_EXCEPTIONS
/*! AWAITING HUGO JSON CONVERSION TOOL 
SIGNATURE NOT RECOGNISED
*/
inline std::error_code error_from_exception(std::exception_ptr &&ep = std::current_exception(), std::error_code not_matched = std::make_error_code(std::errc::resource_unavailable_try_again)) noexcept
{
  if(!ep)
  {
    return {};
  }
  try
  {
    std::rethrow_exception(ep);
  }
  catch(const std::invalid_argument & /*unused*/)
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::invalid_argument);
  }
  catch(const std::domain_error & /*unused*/)
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::argument_out_of_domain);
  }
  catch(const std::length_error & /*unused*/)
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::argument_list_too_long);
  }
  catch(const std::out_of_range & /*unused*/)
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::result_out_of_range);
  }
  catch(const std::logic_error & /*unused*/) /* base class for this group */
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::invalid_argument);
  }
  catch(const std::system_error &e) /* also catches ios::failure */
  {
    ep = std::exception_ptr();
    return e.code();
  }
  catch(const std::overflow_error & /*unused*/)
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::value_too_large);
  }
  catch(const std::range_error & /*unused*/)
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::result_out_of_range);
  }
  catch(const std::runtime_error & /*unused*/) /* base class for this group */
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::resource_unavailable_try_again);
  }
  catch(const std::bad_alloc & /*unused*/)
  {
    ep = std::exception_ptr();
    return std::make_error_code(std::errc::not_enough_memory);
  }
  catch(...)
  {
  }
  return not_matched;
}

/*! AWAITING HUGO JSON CONVERSION TOOL 
SIGNATURE NOT RECOGNISED
*/
inline void try_throw_std_exception_from_error(std::error_code ec, const std::string &msg = std::string{})
{
  if(!ec || (ec.category() != std::generic_category()
#ifndef _WIN32
             && ec.category() != std::system_category()
#endif
             ))
  {
    return;
  }
  switch(ec.value())
  {
  case EINVAL:
    throw msg.empty() ? std::invalid_argument("invalid argument") : std::invalid_argument(msg);
  case EDOM:
    throw msg.empty() ? std::domain_error("domain error") : std::domain_error(msg);
  case E2BIG:
    throw msg.empty() ? std::length_error("length error") : std::length_error(msg);
  case ERANGE:
    throw msg.empty() ? std::out_of_range("out of range") : std::out_of_range(msg);
  case EOVERFLOW:
    throw msg.empty() ? std::overflow_error("overflow error") : std::overflow_error(msg);
  case ENOMEM:
    throw std::bad_alloc();
  }
}
#endif

BOOST_OUTCOME_V2_NAMESPACE_END

#endif

/* utils.hpp
m6vhzalniKv8FNXP6ryn0DlNCXwR4MrzflP1vQLdpV2/416o5uWjPly5szexd9Fm2Y+4yhsv9TXunTvdxHlPT01aWCvtqOs741dUGSN8A415WeSdXufdHAt0lvmUreZvlN1Te087zrQUcOdVM+tYbTMbp0NWu+WkLdrS3DNHO+uZpaV6NdF2eZ3TVnv31a562zWbvYlxT4/M29JyzdL8Gxj10wzXfK4cIdd9ZPpbq+4mdIfIdBrzMc6jPccn0/h1TCVp/1VV/+88HJZrWmVrJ+tojzbabg+bqQ3xMKNYXg/AD/3ocN23WTjceJCDqpPp+V60B9P99Mmm+i5Q0+Xr+q7oBTWvy7vWIw9Vp5n8xn0YLdpXS2I9mmb9UJvK73pO2gK0cNalKYTxW7Gjqjze9EUZxnfTunnm67yq3SQ566r2p+p6rvqrr9afeO9gfi32sLenGlZK1vmWathg72I8x66LN9cv5HovfzLepvQjvTqGkX7ym7V8/b7ehup7Rq9+XiyLwvUsefBTDXmox/CEpJjCY/hcNR/8fR+2VNTOWH7XJnNz4BZbfS9j/Rum1slGnq9osz2M3yUmqvot8g7RWnoXaTeqLZ+jDvtVuZ18C+93HXvHu8J/UMPLSTffwqntTFn57t10nd6Up55KU1urI+1IU9123wFch/6Rb22XW45rVdmO1mc72p7t6Ns+JeQZdabtknyHGSzbpROqjAifaO76P8mvufZbGnub8owaymEt9/erbIHGeY9a115kq1PM9V3A15HyWylZBppKY/cJo9xT2nPaEsoNlnLN7Vfq4yq7hMq3X6tIPmN/8aOqYyWf9vTbbDmnNfPop3Xy5BdsXp2sW+1sh6S9meqrBUk9Tqny6ti3aRf5DWcD07M8EhPM68dZ1f791fxKNu4HGSGPyTT95mpBY+dxri/LOtC4T0rvx/pd0jLfKvsS2WYygabvb1o3UdNhoRyL8Z3QTtVvKd+i+HEE7+PaZh5p6twGB6t0FtnmliRvMc6sBvMOkIEMc46/vSrjkLW1pSt3UvIcR2t3076h8D0CFVUZjWSbXVimv1aCs70pqszC/dJY1z5oehPnMpnF2m609wsqr4dpPAmuebRRDYukdZd1jStL9ftB82KL050hsYzP9Ls3uU9Bjg9U2lkWb0t37nQtYarTU67rU5tVmpZaGRlHSdM4AjlL6qmeKTrY7fRkqHQj2XeUumt61HXpBRy7LuX+HRYaXwxbecO+8zhShg16ifvL1PF8E3We4uPQVL5L5Al5Sc5TRpLPy+bMJ8OiGTbblM9TvsuoRv8o4lnnMNextHmcuS/JtarAtOu2smRmy6Pun6P/ImOc6RXVJSd1zC/DdhHqO+y062Sy+5KgeHHmQdHy80m3U91Hw9HxBlJ5Frtjmm8y/Bd1DJ7xuj5HikkZxvyau4xrs/p4MgfyztTSXsYx83b66cv5gOmZxUZ7PKG202Wk3bC1VNvabM9yWrJn4XVknq1pWk+/VHkCZJ26M4+abqnPPupzUM3PZ5532AMcHlUdHBtobp915Vrm5Dmk7kN4Zos6H7n7XIN0DF/O+YE615i5wPzeC3NZEaTZoM4fZk7mCznTOyfuLCvaKMtvZoK5LHOaKVIWaZ40l2Me3zrS/KrqNMvmKN7lvtOZR9rf1PX7WTUctsB7Tme1FVKmz6zfTedmdz4j37RsEtQ65HvXNsxcZtcVMu4Ss4PM4zXXL5E0anoDZqdzknbPebfISOd4NuleaXYZaXxm/1o0zWt016H7d/n9Q6LEFekmXP19AgrDj5C06vNl1ONL4lvT5yuS7ipek7hOFEj/P9D4zeCNwjLV5z/dnFeqe9P+zW8qTkc=
*/