/* Policies for result and outcome
(C) 2018-2020 Niall Douglas <http://www.nedproductions.biz/> (4 commits)
File Created: Sep 2018


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_OUTCOME_POLICY_FAIL_TO_COMPILE_OBSERVERS_HPP
#define BOOST_OUTCOME_POLICY_FAIL_TO_COMPILE_OBSERVERS_HPP

#include "base.hpp"

BOOST_OUTCOME_V2_NAMESPACE_EXPORT_BEGIN

#define BOOST_OUTCOME_FAIL_TO_COMPILE_OBSERVERS_MESSAGE                                                                                                                                                                                                                                                                              \
  "Attempt to wide observe value, error or "                                                                                                                                                                                                                                                                                   \
  "exception for a basic_result/basic_outcome given an EC or EP type which is not void, and for whom "                                                                                                                                                                                                                         \
  "trait::is_error_code_available<EC>, trait::is_exception_ptr_available<EC>, and trait::is_exception_ptr_available<EP> "                                                                                                                                                                                                      \
  "are all false. Please specify a NoValuePolicy to tell basic_result/basic_outcome what to do, or else use "                                                                                                                                                                                                                  \
  "a more specific convenience type alias such as unchecked<T, E> to indicate you want the wide "                                                                                                                                                                                                                              \
  "observers to be narrow, or checked<T, E> to indicate you always want an exception throw etc."

namespace policy
{
  struct fail_to_compile_observers : base
  {
    template <class Impl> static constexpr void wide_value_check(Impl && /* unused */) { static_assert(!std::is_same<Impl, Impl>::value, BOOST_OUTCOME_FAIL_TO_COMPILE_OBSERVERS_MESSAGE); }
    template <class Impl> static constexpr void wide_error_check(Impl && /* unused */) { static_assert(!std::is_same<Impl, Impl>::value, BOOST_OUTCOME_FAIL_TO_COMPILE_OBSERVERS_MESSAGE); }
    template <class Impl> static constexpr void wide_exception_check(Impl && /* unused */) { static_assert(!std::is_same<Impl, Impl>::value, BOOST_OUTCOME_FAIL_TO_COMPILE_OBSERVERS_MESSAGE); }
  };
}  // namespace policy

#undef BOOST_OUTCOME_FAIL_TO_COMPILE_OBSERVERS_MESSAGE

BOOST_OUTCOME_V2_NAMESPACE_END

#endif

/* fail_to_compile_observers.hpp
TLum02klc7L17YfYd3y3Fni8khzxsp5jXDGYOe7pnNNM6+/xZTTiQkYhX+BHlsSXrSKy2UBibubUKY4Vpvo5lFzlZiizYC79s4rES81tkc6nEH/zGV5zIFW9pxqmew5xzmk2Gijr/Nxch8WwC1cO23G0l53o54ikjfxK2U93h7m162fxz/tZ1vJOn89i3/udn/1N9wfq+lR3DWLTwO1W9n5U9mQtuLR3351v2rvU8SxRPLtQ2sMoOLOT5xm8odFUheOUuV6O9A3n2juk7TFpxwoi1XyhkgMib8t7Q6udC63iuSPW3PtehUVFnGc0Otk5uX6fr4sR5xwRZViFrUSZEwdpA4eb4edv4l4pX0cM89y8EZ53Ec4ko050rpSvfBg1z8pYbblt2sW0/3rIVlekzP2JH/joCnXM39rmLtmTQuYrHHPe9ZVfidIX6v2xzfkv1vbH8WTrmPtoo/z7Q8gNribG866fXaa/EX78FXOvMjU31xm+Q4meOfkeMj9zsfK/IKQeuZnLrmQ/sHpgEvdq5A41VrqjjO3wHXct4yt3c+NCbKny89PPP9ep6Httv/t28V77PY15k3yjsZTTyer6qJDaRqy7lfsJo05IP/t81UcTPN/oNbbd8jRsj12yp2TPyBW7lEPlT7TRTJ73pyr9mpAarBvv73Ibg12hxjjXedjnuu13hMoTg/LVW9k/FPJoCGln1xnGR1PyzUdgcUefq+ytNxqLP+2VPw8wLxZlrCAXNxr1VVwXqHTOIa7S/nOPijQw97ox8KOfWqc6RPlxj/syStMqZLxrkmO9b74957Ouq0or5f9jjOmIZck0s46IP5449XA3MV7Cb8YvtHFDhhjGn3AcEVK6JSS2Zp2IurU930TL9fwhMgaKLP2zdgyEnVVD5FuCsKtqR4REVHK/c4i01zFXdXO218413u9K+7EPOSB8T9qQnVGqHeFvzJxtikvbpvTnMmmTrNqEBobL3iv928SKvdK/UX9HmvvCJxk+Zkn2Htn3JlTeP356l8p7ZI+39QuUnoIfcp6o3zmu+TEyD2i/WxYzr7qMfVVn1FhP6iNmqpwsUGYyZyprmVW7KOXGMqMMYEYZkDZxtIqPWkOn9H92tb/RUPrnkkYPnFP5XUmEbBi6mT4wBN4Fv2tEune320wJvBo1Ot/tzc12zLFdoOzPdye53fpn9u7efaF8gqXvC7Hv1W7J3kfWmL6Nun6Ne4jbM35Ip+3PH057R6wiai8b5xyveo9z7ffFF6jvH0R3GYuUXrPSmoAr5FuZxchxhD5Ryfvy92MOkX4R89PPyZllakgPq0x5v6dUaevVL0p6yfi0g4xPd0r+1UQsRpvzy57ztcx3zir+kWq+KDMDXT8WO+1ZWpXHlfhHmJR/qnzhXspb5T2njsrHKpdK2C5BcrBTKOFT78TVZLfXe3Hpi0uUvfG6MIsf5KA9H1ZoP78uUtdG68qWuJN9uki/4pHynFe7uc8znr0/R5Dvv7zerctcWaFKq8d7Op/h1H77qvItGEq6urbsvu2ZV1+8/IcrovfGdAz7fqT/fez1+5/73zdev09+8OcO6/fJ97ffu/9917uqffVj3rhqZmLSLTW6vfjS9O+aPLk7+P3/9fvPB39OgX4/f//78+vPL/C3v33w5wLo99v3f56Cfv//4Pf51++fH/z+/PrzI/yfv/Cd2i9Y/RhzeNaYNXR71m19CskK9tPDLX+fb3jGHifgfvQd2DHr/ZAQzBx/M75hBOvZt/qo2P8J833yd70QNUZSfk7hfo877D/r+PuQ4++Djr/LxZ8X3Yj8/Ql+noRZ1p6AsBti3qM2zED4qT3HTU6BoXAqbAizYRycARvDXNg=
*/