/* Sets Outcome version
(C) 2017-2020 Niall Douglas <http://www.nedproductions.biz/> (4 commits)


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_MAJOR    2
/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_MINOR    2
/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_PATCH    0
/*! AWAITING HUGO JSON CONVERSION TOOL */
#define BOOST_OUTCOME_VERSION_REVISION 0  // Revision version for cmake and DLL version stamping

/*! AWAITING HUGO JSON CONVERSION TOOL */
#ifndef BOOST_OUTCOME_DISABLE_ABI_PERMUTATION
#define BOOST_OUTCOME_UNSTABLE_VERSION
#endif

/* version.hpp
u1xFcg4nluKOdGbJaiqM9IglPVrqUEX8BCFYzIpFokzsrb2BqTTs6ZyMTBLGgp6SpnRb0qyix2MxyuCxsvwwOjVs6ibWyw1B8MgoUZGnMAQeIBRq0OxRkYYyd8Iu8tpExakj+LupWfsbkk7hDDUHMxrNmrQQRhmPPo/mHyZnc/o8mE4HJ/Nzmryjwck5g30cnRwj9QrGcpK3WS4NjOekllmiZFjZ/HFXr/FEpUFShJKaVhqkqtm4t7SUy1Auiku3bKywKqAgFjmFwoo//jyAaBTKiI7OpmP/eDKc+UeTk9+H09locjJroBE7NJgdjUYoNQ5FpgwBTm4QIKFqRSaRzL8LmQbIY4RAU53ulipZIixWQD68JGpe3L58cXH76mc8w/L/1etmv/FEJkbyflgsl3duIUUdsbt5gYnyOVdWuhz9CynnfCeXIsxs3ucFVKyvo8i3ZNQ/MpGR7Te+9lfR8iL2WMMPRJIsRHDVKlGA4NX7/Fj9SEHbwqNrrULqoMDzrN1g4w886mRax3RArYc7bafHHqrUkkT9HdCOk999u3Kfd6MWW+04m7RPe+0GD6ZcWlQ1PXMypXapWwdJ+we86wB2IFCqbcrs7tYmnIQjkFzcgPvGl/vT1zUmOjxFclV6iRGxuEPzujTWNiq9
*/