/* Proposed SG14 status_code
(C) 2018-2020 Niall Douglas <http://www.nedproductions.biz/> (5 commits)
File Created: Feb 2018


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_OUTCOME_SYSTEM_ERROR2_IOSTREAM_SUPPORT_HPP
#define BOOST_OUTCOME_SYSTEM_ERROR2_IOSTREAM_SUPPORT_HPP

#include "error.hpp"

#include <iostream>

BOOST_OUTCOME_SYSTEM_ERROR2_NAMESPACE_BEGIN

/*! Print the status code to a `std::ostream &`.
Requires that `DomainType::value_type` implements an `operator<<` overload for `std::ostream`.
*/
template <class DomainType,  //
          typename std::enable_if<std::is_same<std::ostream, typename std::decay<decltype(std::declval<std::ostream>() << std::declval<typename status_code<DomainType>::value_type>())>::type>::value, bool>::type = true>
inline std::ostream &operator<<(std::ostream &s, const status_code<DomainType> &v)
{
  if(v.empty())
  {
    return s << "(empty)";
  }
  return s << v.domain().name().c_str() << ": " << v.value();
}

/*! Print the erased status code to a `std::ostream &`.
*/
template <class ErasedType> inline std::ostream &operator<<(std::ostream &s, const status_code<erased<ErasedType>> &v)
{
  if(v.empty())
  {
    return s << "(empty)";
  }
  return s << v.domain().name().c_str() << ": " << v.message().c_str();
}

/*! Print the generic code to a `std::ostream &`.
*/
inline std::ostream &operator<<(std::ostream &s, const generic_code &v)
{
  if(v.empty())
  {
    return s << "(empty)";
  }
  return s << v.domain().name().c_str() << ": " << v.message().c_str();
}

BOOST_OUTCOME_SYSTEM_ERROR2_NAMESPACE_END

#endif

/* iostream_support.hpp
OU9VaTaQpqifOgdvY/f0yX8PhSuvI6S7oPKalJP//LQf3cXk/PRH0vxE/EzQfU88Kf0L4ziOAzVxPF7EtHxtu4uPeG8h9YfrvNSfbrWfmY8J9Htt4V9vA950nquqfeDec9Ve4x0FGULGnhiPxrFj93P3O3ZQxHy/6aos++eHapwBeiP+n0y8TPxJVNOp/fT7vKPruUd/ZqIrrbkuN53jLFzkOCfyM93DdUX1a6AV5o6JtqxjinzXdYNn862vkXTLZ0l3xwlq2F+/n87NulHfV81f5P77quBM/pN35pbCvmiskzmL77dO1B13bu+3W6vGaelpfIPwtYfN3Tog3/t/jxCAK9Xw9p7JXGX8gQhU7UUZj1KW0PtoPbiQ8wuXLM3ry5zvSLXE7r4/6tZSdY/YA+/L+0Llccyjmrbaw3mseGO5uifM1E5PYSTj/OJO3nvUeBZXXf+B6va/67f3ZeXYu0iVw6oHMPRJYhJxmHDegxb5vPv7+dQ1kGWOd8g5y/auKptdy3/PnPMa+4cq/WrqgFQ5vzaNk+8Y3lzK97oqeyPPTZQhT++lteHo/bUlSCtgDaX1VUEbZW2hvWftpBXzSNBm8BT3dz0e52Vc3CV0V/kjPR6jhbRan6aFWspbit+5viOnZvHqHK8813aKy3bRTI0X51FeC+IpC3u07Vy572KxWMqqNLqRRvLO9giiTbHJyvfMHg1d3x8Xv9NeUY+N4DJXcorp3j25t0CWUbKjHHQ518sStazOaeVY8qlsJwvxEMr5ikx7JtO2WGsz38Vd65bM4uRZFabt7TuVvpDrPPAl1d3G46SlmW4c4/pSF3ZLd5zrcAS0F/CyFTSO4yXsVnVN4vgE6u50OedpoF4Lzj9pB8jwTgzfbBrfcfbjqc49AhgWQUx3DM9/LFfTP5LufE59tN2joM2H6Vs5HBfI/14o1/1mah4cz/PvxbgbCMexPt3LwnjqGC/DDhNbiqi8vbzI3e7lYz7equlfJU26v5Fm0jDTswBVui50+9Od4e94V0KO1Isb/NT9iMreDMskZtJ/oukc6Q9i0l117aPdl/jl8rvPlT5a/tfPlQLN10Lybe+B5uu5+bbTQPNzG/Nto4Hm5xyatzep24+o9cJ1Eb+7nxVWJNsxgx2t5IHt8EpJtruV99bt8mt+t9eF/V5Q981qYe6fRUx+D74eHKWGh/Dt3ECL2h+c41CyCO2o6z5s6Z//+RS0+d2+o420j34fv6RV8zdF1ZWDXN8hxqphda29Lb7abQvnG6bf95uvfRRYpY5Bls0656Wu+tPxpJ2B8anqKpXzerG/azoDE+UX7q5jXLQsj39YPKhNPExlSnKdo0WoaQVaPmSpF9ITtcN6FVddUkMNa265QL8717udU7lzj9x5NZ0tLF/On+78bpQfkd35zt1T5VWXq9Zx+st6nOs48aZa5wVd313fVHkNs6j3K2VS90x2XI+0drWF8w4TawNeyuHmHSauY+s2NX511rHNdfyKf1Fdz1fTOM80dqo0pyz3fP8t9yoeV8P3Wx70PuvdKk1V9f5hf9k+h6l+42mrhUha3Ugq06+k+vmrkpj6yTJcrca9bmnDtXn1HtFJXAPOknOgVKNqK6Lqwxz67SKc7zfJyJLzBhl2gpjhGsduPt9ReUZMlutePW0JnO4M5b3FHs73FucxbmmGS97WSON0p5Cc58jwcIZvlu9pOR+zeakamX9avuvYsv4uTXGsP6pmDhxtWIWeNe63/kpitmxLu9kSpa0iy6pG/vfQuLbTxWocq3U+Z/kPWmfDVbru9LuzziYY/f7C+jLmqxvLIGOKrJsmnJ4mq3fJqGFV6T+AkGVoacUytHjJOpLhaYQ=
*/