/* Proposed SG14 status_code
(C) 2018-2020 Niall Douglas <http://www.nedproductions.biz/> (5 commits)
File Created: Feb 2018


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_OUTCOME_SYSTEM_ERROR2_SYSTEM_CODE_HPP
#define BOOST_OUTCOME_SYSTEM_ERROR2_SYSTEM_CODE_HPP

#ifndef BOOST_OUTCOME_SYSTEM_ERROR2_NOT_POSIX
#include "posix_code.hpp"
#endif

#if defined(_WIN32) || defined(BOOST_OUTCOME_STANDARDESE_IS_IN_THE_HOUSE)
#include "nt_code.hpp"
#include "win32_code.hpp"
// NOT "com_code.hpp"
#endif

BOOST_OUTCOME_SYSTEM_ERROR2_NAMESPACE_BEGIN
/*! An erased-mutable status code suitably large for all the system codes
which can be returned on this system.

For Windows, these might be:

    - `com_code` (`HRESULT`)  [you need to include "com_code.hpp" explicitly for this]
    - `nt_code` (`LONG`)
    - `win32_code` (`DWORD`)

For POSIX, `posix_code` is possible.

You are guaranteed that `system_code` can be transported by the compiler
in exactly two CPU registers.
*/
using system_code = status_code<erased<intptr_t>>;

#ifndef NDEBUG
static_assert(sizeof(system_code) == 2 * sizeof(void *), "system_code is not exactly two pointers in size!");
static_assert(traits::is_move_bitcopying<system_code>::value, "system_code is not move bitcopying!");
#endif

BOOST_OUTCOME_SYSTEM_ERROR2_NAMESPACE_END

#endif

/* system_code.hpp
4X5YEz4Pm8MDsBV8BbaGL8CO8BDsAV+GKXLdSqcTcp8ITTrtw57Jp2E4LHe4M4b4d3e77LN9JwyHd0G7XIi7+hp3uyRdHpJ0KYO4U4YJ4m6EuKuLFIu7XrKPfzIMhb1hJEyFrWE/2BEOgT3hUNgbZsAUOBr2h+lwiJgPhSlwuOjW+QRrJRzNJRzO8wmyJPxTYDicCqNhNoyDOTAe5jrKaXkV6XG/+LdD0uMBh7vjQ/yX7zXi7gZYC66Fdn6Lu3oad8vE3XJYF6501ueh/vO7RNzNg+FwvrM+i7vGmvp0u7jbJO7ugNHwXkmvbdBK9zTx5xxNut8k/qyHNeDNkl4bYX24Qfzd6IhPVhXxuUb8u1bCdZ2zXlvh0NTrWeIuX9zNlvvOse7rlrlbmTfOgv2RVpjLt0oq3b+E0fBr2Bh+DxPg32EP+A94Ifwn7A9PweHwR5gOf4Jj4c9wAjSof5nABadDN8yHNeAiWBOugLXgWhgOd8CZcA+cBQ/ChfCPsB78E4yGJ+A58CSMgWbkGsIw2BRGwGYwEp4Hm8DmsA1sC5Pg+XAMvADeAnvDO2AavB/2g4/B/vBpOAw+B4fCl0Q/DkfDj0X/TPRv4Fj4A8yAxN3IgQ1hJmwGs2BruBx2gMWwByyBqXA+HAKvgiPgEngRvBJeDtvBK2AcvFLsLYc94WqYBB8U891wOHwCjoDHxPw47AQ/g51hvRDMJV0jQ2ROTeYCs2AmEhoi+xBK/3wM1oN/gg3gezBO9Hh4HLaDf4ad4UewG9wj5epT9AnwL3AS/AzmwC/gIvgVXAK/hqvhCXgr/AbeJf7cDevBnbA+3AMj4eMwCj4HY+BrsAF8HcbCozAOvgMbw/dgE/gXeC78AjaD+GXEw46wOUyArWBv2Br2hW1gf9gBToAd4SLYBS6FCXAN7Aa3wh7wPpgMH4f9YDkcDt+Eo+H7MB1+BcfAv8Gx8B/wIvgTnABD3YxHYF04G8bCObAJvBgmwiw4Ek6Fl8BsOAXmwGlwJiwQ9wvE/SJYAFfCuXADLIH3wPnwIbgA7oGL4ZNwCSyHV8IDcBk8DJfDo/Aq+D5cAT+GV8Mv4Ur4LbwWfgevgz/D1TAshLEkrAvXwBh4AzwXroUt4DrYHi6DXeAdsAe8E6bBu2F/uAsOhbvhZPhbmAMfhTPhHpgv5vPFfAnEXPapk7ky2FfaY+c+dde4pR2HofB6GAVvgvFwDWwJb4Dd4TrYE94Mk0RPE/0knGjNa8Fucj/nfuBtGCe4YFtYA7aDzWF72Ap2hq1hR3g+7AQTxfwkbIcUiv81EfNZwA2biv+xEp+G0N7nV+w/4iI80LnP7zOyb+izMBq+CNvBQ7AzfAl2g69IPA/DgfCPcDB8FY6AR+DF8HU4Gb4F58N34BXwT3ApfBdeC4/Dm+EHcCv8ED4AP4IPw6/hY/AkfB3+CD+DIaTDKRgKa7hIA9gX1oIDYR04AobDcbA+nAVj4BxohmsZ/ACuhH+BN8h+oOthI3ib6HfBc+EW0Q+Hmut4A19LvM9aQ+xYO7ydxmo/chwxG8+mSBKSgRQiq5Ey5BDyBRL5OX4iGUghsrmvvf5YrStOe4d78/e+3RXriGcgi5GN9pri//71xP8Na4mDWUf8a60h/m9cP7z28+o1xIGsIT6b64c3k+blyDHkByTmC8KKZCCFyEakHPkQifySuCIZSCmyFTmI/IC0+opwIQuQTche5CjyLRL2tVH9q/5V/6p/1b/qX/Wv+lf9q/5V/6p/1b/qX1C/UGTar7X+n3UdJcVFxWrp/1lY+781mudfNZfp/xsi/bct/r4tCv7blrP1rYr+2yX/3wTpv/3x9w1L8N806b+x8v9NkP4=
*/